backend:
  name: github
  repo: seankilleen/seankilleen.github.io 
  branch: main # Branch to update
  site_domain: seankilleen.com # so we can get the github login redirected correctly
publish_mode: editorial_workflow
media_folder: "images/post-images" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "Posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    label_singular: "Post"
    folder: "_posts/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}      
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm ZZ"}
      - {
          label: "Header Image"
          name: header
          required: false
          widget: 'object'
          fields:
            - { label: 'Image URL', name: 'overlay_image', widget: 'string' }
            - { label: 'Opacity', name: 'overlay_filter', widget: 'number', valueType: 'float', default: 0.5 }
            - { label: 'Caption' name: 'caption', widget: string, default: 'Photo credit: [**TODO @ Unsplash**](https://unsplash.com/@TODO?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText)'
        }
      - label: 'References'
        name: 'references'
        required: false
        widget: 'list'
        fields: 
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'URL', name: 'url', widget: 'string', required: true }
          - { label: 'Parent Title', name: 'parenttitle', widget: 'string', required: false }
          - { label: 'Parent URL', name: 'parenturl', widget: 'string', required: false }
    editor:
      preview: false
