name: Build every 2 hours

on:
  schedule:
   - cron: '0 */2 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://api.github.com/repos/seankilleen/seankilleen.github.io/pages/deployments -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.ant-man-preview+json"
